"""
Multi-model AUC robustness check for the predictability-collapse claim.

This script re-estimates within-period renewal predictability using fixed,
simple learners on the existing city-level dataset.npz files:
  - random forest
  - L2-regularized logistic regression

Gradient boosting values are read from the current master table, because they
are the main-text model already generated by the pipeline.

Outputs are written to the national_analysis_dynamic_t1 directory:
  - appendix_A_multimodel_auc_city_period.csv
  - appendix_A_table_A1_predictability_by_classifier.csv
  - appendix_A_table_A1_predictability_by_classifier.xlsx
  - appendix_A_figure_A1_multimodel_auc.png
"""

from __future__ import annotations

import csv
import math
import os
import time
from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import linregress, spearmanr
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


ROOT = Path(os.environ.get("PROJECT_ROOT", ".")).resolve()
RUNS_DIR = ROOT / "city_extract_national/pipeline_runs_dynamic_t1"
ANALYSIS_DIR = ROOT / "city_extract_national/national_analysis_dynamic_t1"
MASTER_CSV = ANALYSIS_DIR / "all79_city_period_master_table_dynamic_t1_with_yearbook.csv"

OUT_DETAIL = ANALYSIS_DIR / "appendix_A_multimodel_auc_city_period.csv"
OUT_TABLE_CSV = ANALYSIS_DIR / "appendix_A_table_A1_predictability_by_classifier.csv"
OUT_TABLE_XLSX = ANALYSIS_DIR / "appendix_A_table_A1_predictability_by_classifier.xlsx"
OUT_FIG = ANALYSIS_DIR / "appendix_A_figure_A1_multimodel_auc.png"

RANDOM_STATE = 42
TEST_SIZE = 0.35
MAX_TRAIN = 50_000
MAX_TEST = 50_000
MIN_CLASS = 5

PERIOD_LABELS = {
    1984: "1984-1990",
    1990: "1990-1995",
    1995: "1995-2000",
    2000: "2000-2005",
    2005: "2005-2010",
    2010: "2010-2015",
    2015: "2015-2020",
    2020: "2020-2024",
}
PERIOD_SHORT = {
    "1984-1990": "84-90",
    "1990-1995": "90-95",
    "1995-2000": "95-00",
    "2000-2005": "00-05",
    "2005-2010": "05-10",
    "2010-2015": "10-15",
    "2015-2020": "15-20",
    "2020-2024": "20-24",
}
PERIOD_MIDYEAR = {
    "1984-1990": 1987,
    "1990-1995": 1992.5,
    "1995-2000": 1997.5,
    "2000-2005": 2002.5,
    "2005-2010": 2007.5,
    "2010-2015": 2012.5,
    "2015-2020": 2017.5,
    "2020-2024": 2022,
}


def clean_city_name(run_dir: Path) -> str:
    return run_dir.name.replace("全流程", "")


def sanitize_X(arr: np.ndarray) -> np.ndarray:
    x = arr.astype(np.float32, copy=False)
    return np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)


def stratified_cap(indices: np.ndarray, y: np.ndarray, max_n: int, seed: int) -> np.ndarray:
    if len(indices) <= max_n:
        return indices
    rng = np.random.RandomState(seed)
    yy = y[indices]
    pos = indices[yy == 1]
    neg = indices[yy == 0]
    if len(pos) == 0 or len(neg) == 0:
        return rng.choice(indices, size=max_n, replace=False)
    pos_n = max(1, round(max_n * len(pos) / len(indices)))
    pos_n = min(pos_n, len(pos))
    neg_n = max_n - pos_n
    if neg_n > len(neg):
        neg_n = len(neg)
        pos_n = max_n - neg_n
    chosen = np.concatenate(
        [
            rng.choice(pos, size=pos_n, replace=False),
            rng.choice(neg, size=neg_n, replace=False),
        ]
    )
    rng.shuffle(chosen)
    return chosen


def make_models():
    return {
        "Random forest": RandomForestClassifier(
            n_estimators=120,
            max_depth=12,
            min_samples_leaf=20,
            max_features="sqrt",
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        ),
        "Logistic regression (L2)": Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                (
                    "clf",
                    LogisticRegression(
                        penalty="l2",
                        C=1.0,
                        class_weight="balanced",
                        solver="lbfgs",
                        max_iter=800,
                        random_state=RANDOM_STATE,
                    ),
                ),
            ]
        ),
    }


def fit_auc(model, Xtr, ytr, Xte, yte) -> float:
    model.fit(Xtr, ytr)
    pred = model.predict_proba(Xte)[:, 1]
    return float(roc_auc_score(yte, pred))


def load_gradient_boosting_from_master() -> pd.DataFrame:
    master = pd.read_csv(MASTER_CSV)
    gb = master[
        [
            "province",
            "city_name",
            "city_name_en",
            "region",
            "city_size_class",
            "period",
            "year_t1",
            "year_t2",
            "samples",
            "updates",
            "update_rate",
            "period_test_auc",
        ]
    ].copy()
    gb = gb.rename(columns={"period_test_auc": "auc"})
    gb["classifier"] = "Gradient boosting"
    gb["status"] = np.where(gb["auc"].notna(), "ok_existing", "missing_existing")
    gb["train_n_used"] = np.nan
    gb["test_n_used"] = np.nan
    return gb


def run_rf_lr() -> list[dict]:
    rows: list[dict] = []
    run_dirs = sorted([p for p in RUNS_DIR.iterdir() if p.is_dir() and p.name.endswith("全流程")])
    total = len(run_dirs)
    models = make_models()

    for ci, run_dir in enumerate(run_dirs, 1):
        city = clean_city_name(run_dir)
        dataset = run_dir / "tculu_pipeline_v9_final/data/dataset.npz"
        if not dataset.exists():
            print(f"[{ci}/{total}] {city}: missing dataset")
            continue
        d = np.load(dataset, allow_pickle=True)
        X = d["X"]
        y = d["is_update"].astype(np.int8) if "is_update" in d.files else d["y"].astype(np.int8)
        years = d["year_t1"].astype(int)
        print(f"[{ci}/{total}] {city}: n={len(y):,}")

        for year_t1, period in PERIOD_LABELS.items():
            mask = years == year_t1
            n = int(mask.sum())
            if n == 0:
                continue
            yp = y[mask]
            n_pos = int(yp.sum())
            n_neg = int(n - n_pos)
            base = {
                "city_name": city,
                "period": period,
                "year_t1": year_t1,
                "year_t2": int(period.split("-")[1]),
                "samples": n,
                "updates": n_pos,
                "update_rate": n_pos / n if n else np.nan,
            }
            if n_pos < MIN_CLASS or n_neg < MIN_CLASS:
                for model_name in models:
                    rows.append(
                        {
                            **base,
                            "classifier": model_name,
                            "auc": np.nan,
                            "train_n_used": 0,
                            "test_n_used": 0,
                            "status": "skipped_too_few_class_samples",
                        }
                    )
                continue

            global_indices = np.flatnonzero(mask)
            local_indices = np.arange(n)
            try:
                tr_local, te_local = train_test_split(
                    local_indices,
                    test_size=TEST_SIZE,
                    random_state=RANDOM_STATE,
                    stratify=yp,
                )
            except ValueError:
                for model_name in models:
                    rows.append(
                        {
                            **base,
                            "classifier": model_name,
                            "auc": np.nan,
                            "train_n_used": 0,
                            "test_n_used": 0,
                            "status": "skipped_split_failed",
                        }
                    )
                continue

            tr_local = stratified_cap(tr_local, yp, MAX_TRAIN, RANDOM_STATE)
            te_local = stratified_cap(te_local, yp, MAX_TEST, RANDOM_STATE + 1)
            Xp = X[global_indices]
            Xtr = sanitize_X(Xp[tr_local])
            ytr = yp[tr_local]
            Xte = sanitize_X(Xp[te_local])
            yte = yp[te_local]
            if len(np.unique(ytr)) < 2 or len(np.unique(yte)) < 2:
                status = "skipped_capped_sample_single_class"
                for model_name in models:
                    rows.append(
                        {
                            **base,
                            "classifier": model_name,
                            "auc": np.nan,
                            "train_n_used": len(ytr),
                            "test_n_used": len(yte),
                            "status": status,
                        }
                    )
                continue

            for model_name, model in make_models().items():
                t0 = time.time()
                try:
                    auc = fit_auc(model, Xtr, ytr, Xte, yte)
                    status = "ok"
                except Exception as exc:  # keep the batch moving.
                    auc = np.nan
                    status = f"failed: {type(exc).__name__}: {exc}"
                print(
                    f"  {period} {model_name:<24} AUC={auc if not math.isnan(auc) else np.nan:.4f} "
                    f"train={len(ytr):,} test={len(yte):,} {time.time() - t0:.1f}s",
                    flush=True,
                )
                rows.append(
                    {
                        **base,
                        "classifier": model_name,
                        "auc": auc,
                        "train_n_used": len(ytr),
                        "test_n_used": len(yte),
                        "status": status,
                    }
                )
    return rows


def summarize_for_table_a1(detail: pd.DataFrame) -> pd.DataFrame:
    ok = detail[(detail["status"].astype(str).str.startswith("ok")) & detail["auc"].notna()].copy()
    records = []
    for clf, group in ok.groupby("classifier", sort=False):
        first = group[group["period"] == "1984-1990"]["auc"].mean()
        last = group[group["period"] == "2020-2024"]["auc"].mean()

        city_slopes = []
        for city, cg in group.groupby("city_name"):
            cg = cg.sort_values("year_t1")
            if cg["period"].nunique() < 3:
                continue
            x = cg["period"].map(PERIOD_MIDYEAR).to_numpy(dtype=float)
            y = cg["auc"].to_numpy(dtype=float)
            if np.isfinite(y).sum() < 3:
                continue
            slope_per_year = linregress(x, y).slope
            city_slopes.append({"city_name": city, "slope_per_decade": slope_per_year * 10})

        slopes = pd.DataFrame(city_slopes)
        pct_down = float((slopes["slope_per_decade"] < 0).mean() * 100) if len(slopes) else np.nan
        mean_slope = float(slopes["slope_per_decade"].mean()) if len(slopes) else np.nan

        x_all = group["period"].map(PERIOD_MIDYEAR).to_numpy(dtype=float)
        y_all = group["auc"].to_numpy(dtype=float)
        rho, p = spearmanr(x_all, y_all) if len(group) >= 3 else (np.nan, np.nan)
        records.append(
            {
                "Classifier": clf,
                "AUC 1984-90": first,
                "AUC 2020-24": last,
                "Slope / decade": mean_slope,
                "% cities ↓": pct_down,
                "Spearman rho": rho,
                "Spearman p": p,
                "N city-periods": int(len(group)),
                "N cities with slope": int(len(slopes)),
            }
        )
    order = ["Gradient boosting", "Random forest", "Logistic regression (L2)"]
    out = pd.DataFrame(records)
    out["order"] = out["Classifier"].map({n: i for i, n in enumerate(order)})
    return out.sort_values("order").drop(columns=["order"])


def plot_figure_a1(detail: pd.DataFrame) -> None:
    ok = detail[(detail["status"].astype(str).str.startswith("ok")) & detail["auc"].notna()].copy()
    summary = (
        ok.groupby(["classifier", "period"], as_index=False)
        .agg(mean_auc=("auc", "mean"), se_auc=("auc", lambda s: s.std(ddof=1) / math.sqrt(len(s))))
    )
    summary["period_order"] = summary["period"].map(PERIOD_MIDYEAR)
    summary = summary.sort_values("period_order")

    colors = {
        "Gradient boosting": "#b53a3f",
        "Random forest": "#2f7da1",
        "Logistic regression (L2)": "#6f5ca8",
    }
    labels = {
        "Gradient boosting": "Gradient boosting",
        "Random forest": "Random forest",
        "Logistic regression (L2)": "Logistic regression (L2)",
    }

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.labelsize": 11,
            "axes.titlesize": 14,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
        }
    )
    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    for clf in ["Gradient boosting", "Random forest", "Logistic regression (L2)"]:
        g = summary[summary["classifier"] == clf]
        if g.empty:
            continue
        x = [PERIOD_SHORT[p] for p in g["period"]]
        y = g["mean_auc"].to_numpy(float)
        se = g["se_auc"].fillna(0).to_numpy(float)
        ax.plot(x, y, marker="o", linewidth=2.8, color=colors[clf], label=labels[clf])
        ax.fill_between(range(len(x)), y - 1.96 * se, y + 1.96 * se, color=colors[clf], alpha=0.12)

    ax.set_title("Figure A1. Predictability decline is robust to model choice", loc="left", fontweight="bold")
    ax.set_ylabel("Mean within-period AUC")
    ax.set_xlabel("Period")
    ax.set_ylim(0.5, 1.0)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False, loc="lower left")
    fig.tight_layout()
    fig.savefig(OUT_FIG, dpi=300, bbox_inches="tight")
    plt.close(fig)


def main():
    ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)
    print("Loading existing gradient-boosting AUCs ...")
    gb = load_gradient_boosting_from_master()
    print("Running Random Forest + Logistic Regression robustness checks ...")
    rf_lr_rows = run_rf_lr()
    rf_lr = pd.DataFrame(rf_lr_rows)

    # Attach metadata from master where possible.
    meta_cols = ["province", "city_name", "city_name_en", "region", "city_size_class"]
    meta = pd.read_csv(MASTER_CSV)[meta_cols].drop_duplicates("city_name")
    rf_lr = rf_lr.merge(meta, on="city_name", how="left")
    detail = pd.concat([gb, rf_lr], ignore_index=True, sort=False)
    detail["period_short"] = detail["period"].map(PERIOD_SHORT)
    detail.to_csv(OUT_DETAIL, index=False, encoding="utf-8-sig")

    table_a1 = summarize_for_table_a1(detail)
    table_a1.to_csv(OUT_TABLE_CSV, index=False, encoding="utf-8-sig")
    with pd.ExcelWriter(OUT_TABLE_XLSX, engine="openpyxl") as writer:
        table_a1.to_excel(writer, sheet_name="Table A1", index=False)
        detail.to_excel(writer, sheet_name="city_period_auc", index=False)

    plot_figure_a1(detail)
    print("Done")
    print(OUT_DETAIL)
    print(OUT_TABLE_CSV)
    print(OUT_TABLE_XLSX)
    print(OUT_FIG)
    print(table_a1.to_string(index=False))


if __name__ == "__main__":
    main()
